### PR TITLE
add commands to cycle through tags

### PR DESCRIPTION
**Pull request by the-other-autumn**
adds two commands:

NextTag which cycles through all tags and loops when it reaches the last tag
` 1->2->3->4->5->6->7->8->9->1 `

PrevTag which cycles through all tags in reverse and loops when it reaches the first tag
`9->8->7->6->5->4->3->2->1->9`

### CODE REVIEW

**Comment by mautamu** [comment]
Hmm, is this the same as FocusNextTag and FocusPreviousTag?

**Comment by the-other-autumn** [comment]
whoops, didn't notice that command

**Comment by mautamu** [comment]
It's all good mate, do you mind sharing where you looked? Would probably be helpful to add some documentation. Want to make leftwm as friendly and easy to understand as possible.

**Comment by the-other-autumn** [comment]
checked through the wiki and the default config file a bit, must have just missed it, 
that's what i get for doing that while im tired i suppose

**Pull request closed without merging**
