### PR TITLE
Add a few window rules

### PR DESCRIPTION
**Pull request by Eskaan**
# Description

Added two window rules mentioned by @VuiMuich on the discord guild. [[here]](https://discord.com/channels/889371782388256818/889532402580488252/1029103113782693998)
- `spawn_fullscreen` spawn in fullscreen.
- `spawn_sticky` spawn sticky.
- `spawn_on_workspace` spawn on workspace. Does not focus the window.

Implemented in #891:
- `behave_as`, now `spawn_as_type` make window behave as different window type.
Documentation was updated correspondingly.

**Not** added were:
- ~~`spawn_on_workspace` because this requires a pretty deep code change to pass the workspaces and tags down.~~
- `spawn_tiled` - Thesis is, that if you specify `spawn_floating: false` it forces the window to be spawned tiled. I couldn't confirm that because I don't have a normal window spawning in floating mode.
- `borderless` - "would require a common way to toggle borders for other windows as well imo" ~VuiMuich

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Updated user documentation:
<details>
<summary>
Intended for the main Config page, Window Rules section, before the first example
</summary>
<hr>

These rules can be applied to the windows:
- `spawn_as_type` Behave as a specific window type. Possible options are `Desktop`, `Dock`, `Toolbar`, `Menu`, `Utility`, `Splash`, `Dialog` and `Normal`.
- `spawn_on_tag` Spawn window on a specific tag number.
- `spawn_on_workspace` Spawn window on workspace id. Does not focus the new window.
- `spawn_floating` Spawn in floating mode. If specified with false, the window will be forced into tiled mode. This will not work with every window, for example some dialogs constantly set themselves into floating mode.
- `spawn_sticky` Spawn window sticky or not.
- `spawn_fullscreen` Spawn window in fullscreen or not.

<hr>
</details>

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by VuiMuich** [comment]
> **Not** added were:
> 
> * `spawn_on_workspace` because this requires a pretty deep code change to pass the workspaces and tags down.
There was some discussion about a `pin tag to workspace` feature (iirc brought up be user smol on discord) that would help to not miss this too much
> * `spawn_tiled` - Thesis is, that if you specify `spawn_floating: false` it forces the window to be spawned tiled. I couldn't confirm that because I don't have a normal window spawning in floating mode.
I am fine with waiting for the first one proofing this thesis wrong :grimacing: 
> * `borderless` - "would require a common way to toggle borders for other windows as well imo" ~VuiMuich
generalising the method of #892 might be a step in this direction

**Comment by VuiMuich** [comment]
Does `behave_as` behave any different then `spawn_as_type` from #891?

**Comment by Eskaan** [comment]
Whoops, it does not. Seems like I did not see the other pr.
Should I remove `behave_as` or add @Sokom141 as Co-author?

**Comment by Eskaan** [comment]
<details>
<summary>
Force push: Corrected merge commit
</summary>
Take one: Make correction

Take two: Actually commit correction
</details>

**Pull request merged**
