### PR TITLE
Exclude NetBSD in `build.rs` and avoid build-hangs

### PR DESCRIPTION
**Pull request by 0323pin**
# Description

Discussion with @VuiMuich on the latest commit.

Fixes build on NetBSD

## Type of change

- [ ] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Updated user documentation:

Please insert user documentation that should be updated (as in the wiki).
Not required.

# Checklist:

- [ ] Ran `make test-full` locally with no errors or warnings reported

`cargo-fmt` is happy 😄

### CODE REVIEW

**Comment by 0323pin** [comment]
Thank you for your interest in my weird issue.

**Comment by VuiMuich** [comment]
😂 I love weird

----
Off-Topic: speaking of, my github behaves a bit weird, with comments in the commits, are you using an app or only the webpage?
For me in the iOS app I can't read the comments at all, and on Chrome and qutebrowser the `read` status refuses to update regularly.

**Comment by 0323pin** [comment]
> Off-Topic: speaking of, my github behaves a bit weird, with comments in the commits, are you using an app or only the webpage?

Webpage on Firefox. Sometimes I post from android but, I haven't installed the app on it. On my mobile I'm using Opera Touch as default browser. Yeah, I know it's not open-source anymore but, I can't stand Firefox mobile version, not since they change the placement of the address bar.

> Chrome and qutebrowser the read status refuses to update regularly.

Not so strange you see the same behavior, both use `qtwebengine` under the hood.

**Comment by VuiMuich** [comment]
> Webpage on Firefox. Sometimes I post from android but, I haven't installed the app on it. On my mobile I'm using Opera Touch as default browser. Yeah, I know it's not open-source anymore but, I can't stand Firefox mobile version, not since they change the placement of the address bar.

Same in Safari, but you can config it back to the top now. I don't use firefox on iOS as it is forced to use WebKit (as are all browsers on iOS).

> Not so strange you see the same behavior, both use `qtwebengine` under the hood.

Didn't know Chrome also uses the `qtwebengine`, I thought this was just a wrapper around the native WebEngine implementation. I would so much love if there was a `qtgecko` or even better a `qtservo` 😁

**Comment by 0323pin** [comment]
> Didn't know Chrome also uses the qtwebengine, I thought this was just a wrapper around the native WebEngine implementation.

Maybe this is the case, I usually don't bother with Chromiun/Chrome/Qutebrowser. I'm back on Firefox after trying to live with BadWolf and Larisa. The state of modern web browsers is depressing and I try not to think about it too much.

**Pull request merged**
