### PR TITLE
add `disable_cursor_reposition_on_resize` option to config

### PR DESCRIPTION
**Pull request by BKSalman**
# Description

personally it annoys me when the cursor snaps to the bottom right corner when resizing, and I searched for an issue to see if anyone agrees, and saw a couple of people, so I'm submitting a PR to add the option to disable it via an option in the config file.

also I just threw together this PR pretty quick, so maybe it needs some changes, so I just wanted to get it out there so we can discuss it here

addresses #1011 

## Type of change

- [ ] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [x] This change requires a documentation update

## Updated user documentation:

this page: https://github.com/leftwm/leftwm/wiki/Config

# Checklist:

- [ ] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not necessary.
- [x] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Review by mautamu — APPROVED** [review]
Looks good as always; went ahead and updated the manpage.

Thank you for this @BKSalman! :smile:

**Comment by BKSalman** [comment]
Thank you for updating the man page, and reviewing! :)

**Comment by BKSalman** [comment]
Thanks for merging! :)

**Comment by VuiMuich** [comment]
Thanks for contributing :partying_face:

**Pull request merged**
