### PR TITLE
Fixed Windows Spawning on Last Tag

### LINKED ISSUE #1065: Window spawns on last tag
### Describe the bug

For a few applications popup windows are spawning always on the last tag even if the parent window is on another tag. Example for this is `virt-manager`. If I want to delete a VM the software asks if I really want to delete  it. This Window is spawned on my tag number 9.

Is this a similar issue as with size-hints?

### Expected behavior (optional)

The popup should spawn on the same tag as the parent window.

### Steps to reproduce (optional)

1. right click on an existing VM
2. select delete
3. and ... nice could not reproduce it now. I reproduced this several times before and now nothing.

## EDIT
Okay finally. I had a mistake with reproduction yesterday.

1. right click on an existing VM
2. select delete
3. Accept delete options.
4. ...and switch to the last workspace to accept the delete warning.

I gathered with xprop the 3 different windows which are opened at this moment:

**virt-manager**
```bash
_NET_WM_USER_TIME(CARDINAL) = 13214442
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x100000b
		bitmap id # of mask for icon: 0x1000013
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 2554, 1404
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777225, 16777226
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000008
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 327 by 140
		program specified base size: 0 by 0
		window gravity: Center
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) = "Virtual Machine Manager"
_NET_WM_ICON_NAME(UTF8_STRING) = "Virtual Machine Manager"
WM_NAME(STRING) = "Virtual Machine Manager"
_NET_WM_NAME(UTF8_STRING) = "Virtual Machine Manager"
```

**delete-options**
```bash
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1000308
		bitmap id # of mask for icon: 0x100030e
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 519, 350
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000007
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777990, 16777991
_NET_WM_USER_TIME(CARDINAL) = 13206491
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000305
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 519 by 350
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) = "Delete Virtual Machine"
_NET_WM_ICON_NAME(UTF8_STRING) = "Delete Virtual Machine"
WM_NAME(STRING) = "Delete Virtual Machine"
_NET_WM_NAME(UTF8_STRING) = "Delete Virtual Machine"
```
**delete-warning-message**
```bash
_NET_WM_DESKTOP(CARDINAL) = 8
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1000935
		bitmap id # of mask for icon: 0x100093b
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 422, 198
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000304
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16779571, 16779572
_NET_WM_USER_TIME(CARDINAL) = 13201963
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000932
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 422 by 198
		program specified maximum size: 422 by 198
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```

Similar behaviour is happening with GIMP if I want to override a file.
##

The Issue might be that I use this crappy dell dock with displaylink, which behaves strange from time to time.

Maybe discuss further in Discord?

### Relevant log output (optional)

_No response_

### OS / Distro

Linux arch-dell-latitude7430 6.3.3-arch1-1

### Additional System Information (optional)

_No response_

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 438b073
:: Enabled features: default journald-log lefthk lefthk-core tracing-journald
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron

Theme is slightly updated Ascent don't where the repo moved to
```

### PR DESCRIPTION
**Pull request by Silicasandwhich**
# Description

Fixed a bug where windows would sometimes spawn on the last tag. As far as I can tell, the issue was with a degenerate case in ```score_window``` ([config.rs](https://github.com/Silicasandwhich/leftwm/blob/last_tag/leftwm/src/config.rs) l line 98) when the window title is an empty string. I'm  sure that there are more elegant ways to deal with this, but I just made a check explicitly before ```score_window``` is called in ```setup_predefined_hooks``` so that, unless there's explicitly a window rule that's supposed to match empty windows, the window is ignored.

Also, the git diff shows a lot more changes than are actually new to the codebase because I forgot to sync my fork with upstream before working on it, but as far as I can tell, the only thing actually getting changed is config.rs.

Fixes #1065 

## Type of change

- [ ] Development change (no change visible to user)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

## Updated user documentation:

N/A

# Checklist:

- [X] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not neccesary.
- [X] Manual page has been updated accordingly
- [X] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by VuiMuich** [comment]
No worries about the bunch of extra commits, will squash anyways and the actual diff is only 14 lines 👍

I did a quick build with merges `main` and `leftwm-layouts` branch and a quick test with virtmanager; so far all looking good to me.

@MaKaNu would you have the possibility to build this PR and live test in your side?

**Comment by MaKaNu** [comment]
Hi I didn't tested the merge request state until now, but was able to build the branch last_tag. Sadly the problem with thunderbird still occurs if I use the spawn_on_tag config

**Comment by Silicasandwhich** [comment]
okay, interesting. is the problem just with thunderbird? (e.g. is virt-manager fixed for you?)

**Comment by Silicasandwhich** [comment]
okay, ive tested the new changes on a clean machine. now, when the following window rule is in effect:
```rust
    (window_class: "thunderbird", spawn_on_tag: 3),
```
all thunderbird windows spawn on tag 3. when said rule is removed from my config, they all spawn on the current active tag, which i believe is the intended behavior. if that wasn't the problem and there's something else that needs fixing, please let me know

**Comment by MaKaNu** [comment]
I was completely dumb. I work a lot with git but totally forgot to switch branches while testing the first time now I am on the correct brunch and on my test rig the windows are spawning where they should. I am curious might that also be an approach for the missing size hint windows? Since I know have a working Test VM I might finally evolve my rust skills (sadly still not finished the book...)

**Comment by MaKaNu** [comment]
What does cargo testing not like with empty strings?:

`comparison to empty slice`

**Comment by Silicasandwhich** [comment]
found the issue, it wanted ```str.is_empty()``` instead of ```str == ""```. should be fine otherwise. i didn't catch it because i thought the clippy CI test would fail if it detected something wrong, so i didn't check the output.

**Comment by Silicasandwhich** [comment]
oops, i changed the version number so i knew that i was running the edited version, i reverted it so it should be good to merge now

**Comment by VuiMuich** [comment]
When we can get positive confirmation by @MaKaNu we can merge this.

**Comment by VuiMuich** [comment]
Just a nitpick: might be nice ta add a little explanation for future code reviewers, about the details, as it might not be obvious at a glance why those binary operations are that way.

**Comment by Silicasandwhich** [comment]
> Just a nitpick: might be nice ta add a little explanation for future code reviewers, about the details, as it might not be obvious at a glance why those binary operations are that way.

i added a note, tell me if it's too long or unclear

**Comment by VuiMuich** [comment]
I think it's great, thanks!

**Pull request merged**
