### PR TITLE
better clap and fix broken `workspace` flag for `leftwm-state`

### LINKED ISSUE #933: Latest commits break functionality
### Describe the bug

Until today I was running a build from 049a6b4a4f4881013c6f5029cbd057535332a370
Where, I've actually posted a question on the commit itself that has passed unnoticed.

Today, I did a rebuild from f4c45205f5558a0c9dfc3f2206f8b6b8c7c315da and hit several issues. Somethings are working but, most of it is not. Wallpaper is applied but, the bar is missing. Keybinding to launch programs work but, binding to switch from one window to another are not. Also window decorations, like borders are the default ones and not from my theme.

Not much but, see leftwm-check bellow

Any thoughts?

For now, I've reverted back to 049a6b4a4f4881013c6f5029cbd057535332a370 where I still have to figure out how to use the new leftwm-config command? But, priority to investigate what broke.

### Expected behavior (optional)

_No response_

### Steps to reproduce (optional)

_No response_

### Relevant log output (optional)

_No response_

### OS / Distro

NetBSD-9.99.102, Rust-1.64.0

### Additional System Information (optional)

_No response_

### LeftWM Check

```text
~ > leftwm check
thread 'main' panicked at 'ArgAction::Count is defaulted', /usr/pkgsrc/wip/leftwm/work/vendor/clap-4.0.18/src/parser/matches/arg_matches.rs:144:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception: leftwm exited with 101
[tty 2], line 1: leftwm check

~ > RUST_BACKTRACE=1 leftwm check
deprecation: the legacy temporary assignment syntax is deprecated; use "tmp" instead
[tty 3], line 1: RUST_BACKTRACE=1 leftwm check
thread 'main' panicked at 'ArgAction::Count is defaulted', /usr/pkgsrc/wip/leftwm/work/vendor/clap-4.0.18/src/parser/matches/arg_matches.rs:144:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception: leftwm exited with 101
[tty 3], line 1: RUST_BACKTRACE=1 leftwm check
```

### PR DESCRIPTION
**Pull request by TornaxO7**
# Description

Bugfix and refactored some stuff

Fixes #933

## Type of change

- [ ] Development change (no change visible to user)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

## Updated user documentation:

Not needed

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not neccesary.
- [x] Manual page has been updated accordingly
- [x] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by VuiMuich** [comment]
To be honest, I am not very fond of the single use `const`, but this might be my very personal opinion, and if others find it useful I am happy to accept this.
To me a `const` makes sense in two cases, that might overlap at times:
- you have a config section in the code where you can easily set personal preferences
- you have the same constant used in a bunch of places (and specifically for Rust, don't want to worry about lifetimes)
But in this case the `SOMETHING_ARG` references make me jump through the code just to see what the actual string is.

**Comment by VuiMuich** [comment]
Hey thats not fair just when I sent that message to push a commit that does exctly this :wink:

**Comment by VuiMuich** [comment]
BTW, while you are at this part already: earlier today I noticed in `leftwm.rs` we have a `print_help` method, that would have some nice message, but we don't print it (anymore I guess).
Also `leftwm help` promises to work for subcommands but it doesn't.

**Comment by Eskaan** [comment]
I was just faster telling him the exact same thing in the Discord channel haha

**Comment by TornaxO7** [comment]
> BTW, while you are at this part already: earlier today I noticed in leftwm.rs we have a print_help method, that would have some nice message, but we don't print it (anymore I guess).

What do you mean?

**Comment by Eskaan** [comment]
@VuiMuich about the print_help function.
Defined here: https://github.com/leftwm/leftwm/blob/d8d39518fc656279f0223ed602cdbb83a72c9748/leftwm/src/bin/leftwm.rs#L68
Used here: https://github.com/leftwm/leftwm/blob/d8d39518fc656279f0223ed602cdbb83a72c9748/leftwm/src/bin/leftwm.rs#L108-L114
It is always printed, if the subcommand is unrecognized, including `-h` and `--help`, because they are nowhere defined.

**Comment by VuiMuich** [comment]
> > BTW, while you are at this part already: earlier today I noticed in leftwm.rs we have a print_help method, that would have some nice message, but we don't print it (anymore I guess).
> 
> What do you mean?

`leftwm/src/bin/leftwm.rs:67:90`:
```rust
/// Prints the help page of leftwm (the output of `leftwm --help`)
fn print_help_page() {
    let subcommands = {
        let mut subcommands = Vec::new();
        for entry in AVAILABLE_SUBCOMMANDS {
            let subcommand_name = entry[SUBCOMMAND_NAME_INDEX];
            let subcommand_description = entry[SUBCOMMAND_DESCRIPTION_INDEX];

            subcommands.push(clap::Command::new(subcommand_name).about(subcommand_description));
        }
        subcommands
    };

    command!()
        .long_about(
            "Starts LeftWM if no arguments are supplied. If a subcommand is given, executes the \
             the corresponding leftwm program, e.g. 'leftwm theme' will execute 'leftwm-theme', if \
             it is installed.",
        )
        .version(env!("CARGO_PKG_VERSION"))
        .subcommands(subcommands)
        .print_help()
        .unwrap();
}
```
This `long_about` is nice but I couldn't make it show.

**Comment by Eskaan** [comment]
Edit: This is only one of the subcommands

**Comment by VuiMuich** [comment]
I am gonna merge, as to fix the broken `leftwm-state`.
Any further and welcome enhancements to `clap` go in a separate PR please.

Thanks @Eskaan for greatly supporting this PR and thanks @TornaxO7 for being this quick at the ready to fix things.

**Comment by Eskaan** [comment]
Wait please

**Pull request merged**
