### PR TITLE
added lefthk feature checks and errors

### PR DESCRIPTION
**Pull request by OfekShochat**
# Description
add lefthk feature check to leftwm-check, and error reporting.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

- [x] Ran `make test-full` locally with no errors or warnings reported

### CODE REVIEW

**Comment by VuiMuich** [comment]
Just one thing: if features is empty, i.e. when building with `--no-default-features`, we should probably state this explicitly.

**Comment by OfekShochat** [comment]
Ok, what should it write instead?

**Comment by OfekShochat** [comment]
Also, no default features doesn't say it wasn't built with any. So, should I return when the default feature is disabled?

**Comment by OfekShochat** [comment]
ran test-full this time, sorry

**Review by VuiMuich — CHANGES_REQUESTED** [review]
Despite those minor suggests, LGTM

**Review by VuiMuich — APPROVED** [review]

**Pull request merged**
