### PR TITLE
Configurable new window behavior

### PR DESCRIPTION
**Pull request by kid**
This implements #358 and allows configurable behavior for new windows.

### CODE REVIEW

**Comment by kid** [comment]
Probably needs a better name than `insert_behavior`, maybe `new_window_mode`?

**Comment by kid** [comment]
Also, I'm not sure what to do with Monocle and `MainAndDeck`, as I'm not sure why they are special cases in `insert_window` (I can guess why for `Monocle`, but `MainAndDeck` is a bit of a mystery :thinking: )

**Comment by kid** [comment]
Marking as ready now that it has tests, but I'm just not sure about the naming

**Comment by VuiMuich** [comment]
> Also, don't know what to do with Monocle and `MainAndDeck`, as I'm not sure why they are special cases in `insert_window` (I can guess why for `Monocle`, but `MainAndDeck` is a bit of a mystery thinking )

Will get into this PR later, but want to leave this comment right now:
The deck behaves in most cases like the monocle, but further special, as the top window remains always separated from it.

I hope this makes sense to you.

**Comment by kid** [comment]
does it makes sense to handle at least `InsertBehavior::Top` (and maybe InsertBehavior::BeforeCurrent` ?) as well for `MainAndDeck`

**Comment by mautamu** [comment]
Was quietly force-pushed, should be ready to go now. Thanks for the quick update @kid! Probably wise to go after #594 but before #638

**Pull request merged**
