### PR TITLE
fix theme paths with spaces

### PR DESCRIPTION
**Pull request by AethanFoot**
Hopefully fixes theme paths that include spaces, as discussed on the discord.
Thanks

### CODE REVIEW

**Comment by VuiMuich** [comment]
Hmm, unfortunatelly I get this in journalctl:
`leftwm-worker[444325]: Could not load theme at path ~/.config/leftwm/themes/Blue\ Coffee/theme.toml: No such file or directory (os error 2)`
for `leftwm command "LoadTheme ~/.config/leftwm/themes/Blue\ Coffee/theme.toml"`
```
leftwm check
:: LeftWM version: 0.2.9
:: LeftWM git hash: 0182aaf
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
This works, but only with absolute path.
Relative path errors in journalctl with
```
leftwm-worker[444325]: Could not load theme at path ~/.config/leftwm/themes/Blue Coffee/theme.toml: No such file or directory (os error 2)
```
But this is due to a lack ot `std::path` to handle relaive paths, iirc.

**Comment by AethanFoot** [comment]
Will sort it tomorrow now.
Thanks.

**Comment by AethanFoot** [comment]
To actually support ~/ (which a shell expansion) I needed to add a crate shellexpand.
Thanks.

**Comment by VuiMuich** [comment]
Hey, shellexpansion will also help me with #480 I guess. Thanks!

**Pull request merged**
