### PR TITLE
add layouts to config

### PR DESCRIPTION
**Pull request by Stanislav-Lapata**

### CODE REVIEW

**Comment by lex148** [comment]
@Stanislav-Lapata This is great work, Thanks. We have really needed this for a while. I have two small requests before I press the merge button. 

- For some reason. I can only press (Mod+Crtl+⬆️) two times. After that It stops working. This could be something I did. Would you please check to make sure you didn't introduce a bug here. 
- Would you please add a couple of words about this to the README.md file. We don't and shouldn't explain everything there, but letting people know this exist is important. We can add more info in the wiki

Again awesome work and thank you. 

shoot me a message when you think its ready to go.

**Comment by Stanislav-Lapata** [comment]
@lex148 Sorry for long time answer. And sorry for my English. A can't reproduce your problem. Layouts changes correctly when I use NextLayout/PreviousLayout commands. I added minimal info to the README.md.
Do you have any other comments?

**Comment by lex148** [comment]
Great, I will give it another round of testing. Thanks again for your Pull Request.

**Comment by VuiMuich** [comment]
> * For some reason. I can only press (Mod+Crtl+arrow_up) two times. After that It stops working. This could be something I did. Would you please check to make sure you didn't introduce a bug here.

@lex148 I have not tested this PR and maybe it's something unrelated all along, but in my monocle layout I experience something similiar: when cycling through windows or layouts sometimes it takes two keystrokes to execute the command, but have not put too much into it, given the other remaining issue of this layout. It seams that this might occur, when the list gets started over again.

**Comment by lex148** [comment]
@Stanislav-Lapata fine work on this Pull Request. I really appreciate your contribution.

**Pull request merged**
