### PR TITLE
adding rust-toolchain.toml

### PR DESCRIPTION
**Pull request by TornaxO7**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Updated user documentation:

Please insert user documentation that should be updated (as in the wiki).

See [CONTRIBUTING.md User Documentation section](../CONTRIBUTING.md#user-documentation) for further details.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test` locally with no errors or warnings reported
- [x] Enhanced review is performed with `cargo clippy -- -W clippy::pedantic -A clippy::must_use_candidate -A clippy::cast_precision_loss -A clippy::cast_possible_truncation -A clippy::cast_possible_wrap -A clippy::cast_sign_loss -A clippy::mut_mut`
- [x] Manual page has been updated accordingly
- [x] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by VuiMuich** [comment]
What do you think of adding `rust-toolchain.toml` to `.gitignore` so if someone wants to regularly build agains `nightly` or some specific version, or what ever can easily do without running into trouble when commiting, but we enforce `stable` as default.

**Comment by TornaxO7** [comment]
Hm... I don't think that this would be useful, because it could happen that this person gets some errors on the nightly version while the stable works (ok, they could remove the `rust-toolchain.toml` but still...)

**Comment by VuiMuich** [comment]
> Hm... I don't think that this would be useful, because it could happen that this person gets some errors on the nightly version while the stable works (ok, they could remove the `rust-toolchain.toml` but still...)

But that's basically the same as it is right now, isn't it? My reasoning would be that someone who decides to build with `nightly` against the default toolchain is aware enough of what they are doing to care to check if their commit runs well with `stable` as well.

**Comment by TornaxO7** [comment]
Well, if you really insist in doing that, I can't complain, then.

**Pull request closed without merging**
