### PR TITLE
Dirty clickto fix

### PR DESCRIPTION
**Pull request by AethanFoot**
Okay, I have tried everything under the sun to try and get ClickTo with the replay_pointer with XAllowEvent (which is a much cleaner way and seems to be what most use). However the button grabs seem to just crash whenever pointer mode is in sync (needed for the current replay_pointer and what most wm's seem to prefer to use).

So I said f*** it and made all the button grabs have async pointer mode, and manually play a click where the pointer is and send it to the window the pointer is on.

I need to add the replay for right clicks but just wanted to test if this actually is stable.
Thanks!

### CODE REVIEW

**Comment by VuiMuich** [comment]
Same as with the `lefthk` PR, IMO you could resolve conflicts and merge in one go.

**Comment by VuiMuich** [comment]
:thinking: I guess the quick resolve via the github web editor was a fail :joy:
Sorry I put the extra step to revert [d467d25](https://github.com/leftwm/leftwm/pull/696/commits/d467d25f0f2b4ed5062034e88f546760c21aef2c) on the list to get this merge ready, @AethanFoot.

**Comment by AethanFoot** [comment]
Ill sort these tomorrow when I have time.

**Comment by VuiMuich** [comment]
Ohh, for some reason the commit via the web editor did push the unedited file and ignored my resolved file. I wonder how that was possible. No wonder the compilation broke.
At least the fix is trivial...

**Comment by VuiMuich** [comment]
:relieved: glad this worked out now...

**Pull request merged**
