### PR TITLE
Fixed wrong Monocle and MainAndDeck focus in Driven and ClickTo focus behaviour

### PR DESCRIPTION
**Pull request by Syudagye**
This PR fixes a problem i have with the `driven` focus behavior:
When i switch to the Monocle layout, if i don't focus the main window, the focused widow will be hidden and i will never be able to interact with the currently visible window, because it doesn't have focus.

**How to replicate this situation :**
- set `focus_behaviour = "Driven"` in `config.toml`
- open some windows on a tag
- focus a window other than the main one
- switch to Monocle

**wrong behaviour :** The main window get the full area but doesn't have the focus.

**fixed behaviour :** The main window get the focus.

### CODE REVIEW

**Comment by Syudagye** [comment]
No idea what happened with git complaining about merge conflicts, but it seems fine now

**Comment by VuiMuich** [comment]
Commencing test 😆

**Comment by VuiMuich** [comment]
I had one situation, where the windows of a tag with layout `MainAndDeck` got 'detached' aka unfocusable after switching to it from a tag where I followed the steps in OP. But I cent reproduce it a second time.

**Comment by Syudagye** [comment]
> _sidenote: should we change (not necessarily in this PR) that when we switch to layout `Monnocle` the focused window becomes main? Currently the main window is put on top, no matter it had focus before or not._

I thought of this while trying to find a way to fix this, but couldn't find a way to do it. But yes that would feel more natural.

**Comment by AethanFoot** [comment]
@VuiMuich would you say this is ready? Were you able to reproduce the issue.

**Comment by VuiMuich** [comment]
I'll be back on my machine in about 3h. Will give it another try to reproduce. If I can't I'm gonna merge.

**Comment by VuiMuich** [comment]
I tried hard but could not reproduce my earlier issue with `MainAndDeck` so lets assume this was an unrelated issue.

Thanks @Syudagye for your fixes!

**Pull request merged**
