### PR TITLE
Added information section on floating windows.  Reformatted Default K…

### PR DESCRIPTION
**Pull request by rebuilt**
…eys section for readability

### CODE REVIEW

**Comment by VuiMuich** [comment]
Just a little nitpick: you could indent the arrows on the keybinds to the same column as the in the floating section for consistent alignment.

**Comment by rebuilt** [comment]
The arrow symbols take up more than a single character of spacing.  This resulted in uneven spacing despite having the same number of spaces in the markdown file.  Reducing the number of spaces got it closer to correct alignment, but you're right, it still looks messy.  I think turning it into a table might fix the alignment.  I'll try that.

**Comment by VuiMuich** [comment]
That's great with the tables! This results in even more mobil friendly display.

**Comment by mautamu** [comment]
Appreciate this! Will cross reference and update mautamu/leftwm_wiki for merging hopefully later tonight.

**Comment by rebuilt** [comment]
Thanks!   This will be my first real pull request.

**Pull request merged**
