### PR TITLE
Add 'args' Scratchpad config entry

### LINKED ISSUE #1223: Scratchpad commands should support arguments
### Describe the enhancement

Due to the changes in #1216, scratchpad commands do not seem to take arguments. E.g. `mpv` works fine, but `mpv test.mp4` doesn't seem to work.

I have multiple scratchpads that launch chromium instances in kiosk mode with a specific data directory and URL. I use these as apps effectively (e.g. for Youtube music). Here's an example scratchpad config:
`name: "yt_music", value: "chromium --user-data-dir=\"/home/black/etc/yt_music_chromium\" --kiosk --disable-session-crashed-bubble \"https://music.youtube.com\""`

This worked fine for me. Once started, pressing the key combination for the associated `ToggleScratchpad` command hid the browser and the music kept playing in the background.

This is very useful for me, so I reverted the changes locally to `child_process.rs` to get it to work again.
I think it would be useful to support arguments in general. 

I guess the value of the Scratchpad config's `name` parameter could be split and passed to the `args` to builder method, but that seems a bit weird. Also, arguments could be passed to the Scratchpad config as a config parameter, if that makes sense.

### How important is this enhancement to you?

My workflow is impaired without it

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

### PR DESCRIPTION
**Pull request by mautamu**
# Description

This adds a new optional field for scratchpads that allows their child process to be called with arguments.

Fixes #1223
History of the art: #1216, #958.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Updated user documentation:

> # Scratchpads
> 
> A scratchpad is a set of windows which you can call to any tag and hide it when not needed. These windows can be any set of application which can be run from a terminal. To call a scratchpad you will require a keybind for [ToggleScratchPad](#togglescratchpad). When you want to manipulate the currently focused scratchpad, other commands like [ReleaseScratchPad](#releasescratchpad), [AttachScratchPad](#attachscratchpad) and [NextScratchPadWindow/PrevScratchPadWindow](#nextscratchpadwindowprevscratchpadwindow) are available.
> 
> Example:
> 
> ```rust
> scratchpad: [
>     ( name: "Alacritty", // This is the name which is referenced when calling (case-sensitive)
>       value: "alacritty", // The command to load the application if it isn't started (first application to start)
>       args: ["-e", "python"], // Any arguments to pass to the command
>       // x, y, width, height are in pixels when an integer is inputted or a percentage when a float is inputted.
>       // These values are relative to the size of the workspace, and will be restricted depending on the workspace size.
>       x: 860, y: 390, height: 300, width: 200 
>     ),
> ]
> ```
> 
> **Note: The scratchpad and `ToggleScratchPad` are only available in LeftWM >=0.2.8, the other scratchpad manipulating commands in LeftWM > 0.2.11**, and `args` in >0.5.1.

See [CONTRIBUTING.md User Documentation section](../CONTRIBUTING.md#user-documentation) for further details.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not necessary.
- [x] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by mautamu** [comment]
Hey @akosfekete!

Below patch should resolve the issues with this PR:

[0001-chore-update-documentation-formatting.patch.txt](https://github.com/leftwm/leftwm/files/14149413/0001-chore-update-documentation-formatting.patch.txt)

**Comment by VuiMuich** [comment]
Thanks for taking care of this topic @mautamu.
I was trying to find a solution for this myself, but with a different approach, I tried to keep the args in the value and split the string like this:
```rust
/// Sends command to shell for execution
/// Assumes STDIN/STDERR/STDOUT unwanted.
pub fn exec_shell(command_string: &str, children: &mut Children) -> Option<ChildID> {
    let (command, arguments) = command_string
        .split_once(" ")
        .unwrap_or((command_string, ""));
    tracing::info!("Scratchpad command {:?} and args {:?}", command, arguments);
    let child = Command::new(command)
        .args(arguments.split_whitespace())
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let pid = child.id();
    children.insert(child);
    Some(pid)
}
```
But neither mine nor yours is currently working for me, I hope I have more time to test it in depth tonight after work.

Here is my scratchpad config (original one commented out):
```rust
scratchpad: [
        // (name: "ScratchpadTerminal", value: "alacritty", x: 0.055, y: 65, width: 0.89, height: 0.34),
        // (name: "ScratchpadTerminal", value: "alacritty -t ScratchPad", x: 0.055, y: 65, width: 0.89, height: 0.34),
        // (name: "BTop", value: "alacritty -t BTop -e btop", x: 10, y: 65),
        // (name: "LeftWMConfig", value: "alacritty -t \"LeftWM Config\" -e hx -c ~/.config/helix/lwmc_config.toml ~/.config/leftwm/config.ron", x: 0.055, y: 577, width: 0.89, height: 0.55),
        (name: "ScratchpadTerminal", value: "alacritty", args: ["-t", "ScratchPad"], x: 0.055, y: 65, width: 0.89, height: 0.34),
        (name: "BTop", value: "alacritty", args: ["-t", "BTop", "-e", "btop"], x: 10, y: 65),
        (name: "LeftWMConfig", value: "alacritty", args: ["-t", "\"LeftWM Config\"", "-e", "hx", "-c", "~/.config/helix/lwmc_config.toml", "~/.config/leftwm/config.ron"], x: 0.055, y: 577, width: 0.89, height: 0.55),
        (name: "DynamicScratchpad", value: ""),
    ],
```

**Comment by akosfekete** [comment]
Thanks for looking at this issue, @VuiMuich! I copied one of your scratchpad configs and it seems to work fine for me with code from this branch using the ToggleScratchpad command (you can see the terminal title change in polybar). 


https://github.com/leftwm/leftwm/assets/36549157/6a881588-399d-4481-baac-aa25be0d0b44


 Although splitting the command could be better in the sense that it breaks less people's configs with the next release.

**Comment by mautamu** [comment]
Thanks again for looking into this VuiMuich and akosfekete! All credit to akosfekete, I just opened the PR from akosfekete's branch. 

I think breaking the string would be preferable, provided there isn't some nuance to the shell scripting that we'd inadvertently damage.

**Comment by VuiMuich** [comment]
Finally I had the possibility to do some testing today, it pretty much looks like I have a general issue with my NixOs rig, that the "local builds" are not used in my live system for reasons I currently don't understand.
Using the nixos-vm script introduced with the flake reworks last summer I was able to reproduce this PR working. Just one thing, I wanted to test was not possible in the VM was if there are things not working properly when `nushell` is used as `chsh` system shell.
If somebody would have a chance to check this corner case it would be great, otherwise I am willing to do the `live test` post merge :grimacing: 

One tiny thing that might be nice to add bevor merging would be a debug log of the scratchpad args, just to be clear that this gats processed correctly, no?

**Comment by mautamu** [comment]
Thanks @akosfekete!

This looks good to me, but will wait to see if others have any additional comments cc: @VuiMuich / @Eskaan

**Comment by VuiMuich** [comment]
Lgtm and I'm happy if we get this into main.
The config option can easily be a separate PR.

**Comment by mautamu** [comment]
Thanks again @akosfekete for driving this home and Eskaan and Vuimuich for reviewing! :) 

Will merge this and submit a follow-on PR for fixing the clippy warning since akosfekete:scratchpad_args is protected.

**Pull request merged**
