### PR TITLE
updated README

### PR DESCRIPTION
**Pull request by Pungolo**
Added gentoo overlay and info

### CODE REVIEW

**Comment by VuiMuich** [comment]
Welcome adventurer!
Thanks for this contribution. 
Are you also maintaining the package for gentoo?

**Comment by Pungolo** [comment]
Yes my friend. Y can also find me on discord: Adàhy #4629

Cordiali Saluti
Degni Luciano

Il 5 gen 2022, 10:01 +0100, VuiMuich ***@***.***>, ha scritto:

**Comment by VuiMuich** [comment]
Almost expected this 😃

**Comment by Pungolo** [comment]
Lol an easy deduction

Cordiali Saluti
Degni Luciano

Il 5 gen 2022, 15:18 +0100, leftwm/leftwm ***@***.***>, ha scritto:
>
> Almost expected this 😃

**Pull request merged**
