### PR TITLE
Fix crash when swapping tag at startup

### PR DESCRIPTION
**Pull request by cecton**
# Description

When leftwm has just started and you swap tag (the shortcut that swaps between
the last and the current tag), it crashes on the `unwrap()`. This is because
there is no last tag in the history.

## Type of change

Bug fix

## Updated user documentation:

I guess none.

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not neccesary.

### CODE REVIEW

**Comment by VuiMuich** [comment]
Thanks!

This should close #971 then.

**Comment by VuiMuich** [comment]
Thanks for fixing their merge conflict.

**Comment by cecton** [comment]
There was none locally :woman_shrugging: I guess github is not using the same conflict resolution algorithm than git

**Comment by VuiMuich** [comment]
:thinking: this is odd. Looking at the of the first commits' diff in the browser it looks like github was thinking this PR is based on a merged #984.

**Comment by cecton** [comment]
GitHub works in mysterious ways sometimes :woman_shrugging: 

It was based on an older commit though. The parent commit is 2840e5ace1f7e293d9c2e37feebcc31b71b888e0

Well. Either way, it works and it's nice that I accidentally fixed some issue haha xD

**Comment by VuiMuich** [comment]
Oh, now I get it, I guess. I the mean time there was some refactor on the commandhandler, that modularised it with the subdirectory structure and it was by pure chance, that almost at the same time you created this PR, I opened #984, wich renames all the `mod.rs` files, so I guess it got me confused for a moment.

**Pull request merged**
