### PR TITLE
Refactor window sorting

### PR DESCRIPTION
**Pull request by Eskaan**
# Description

- Refactor to the window sorting to a cleaner solution.
- Refactor `Window.states` to `pub` (set and get methods were there, so why not make it it pub)
- Move from manually getting transient windows whilst sorting windows to adding the `Above` WM state to them.
- Side-effect: We now sort windows with the `Above` WM state on top of everything. Windows set this property on their own.

## Type of change

- [x] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
  - As the window sorting now understands the `Above` WM hint, windows can set themselves to be on top.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - This pr places unmanaged windows above **all** windows instead of all but fullscreen. A visible unmanaged window is yet to be found, so it's not marked as breaking.
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not necessary.

### CODE REVIEW

**Comment by Eskaan** [comment]
@VuiMuich I am currently questioning myself above what windows such a transient window should be placed. Should we stay at the old solution (if parent fullscreen, above all, otherwise threat normal)?
I could also go with my next pr and automatically mark such windows as `OnTop` so that you can push them back on demand.

**Comment by VuiMuich** [comment]
How would pushing them back on demand work? Would it be a new command or just with unfocusing?
Generally this sound like a nice idea to me.
The old solution was just done like this for the lack of a better idea, I guess.

**Comment by Eskaan** [comment]
> How would pushing them back on demand work?

I want to implement the `OnTop` Window State that, when enabled and the window is floating, forces the window to the first layer. Then I would give every transient window which has a fullscreen parent that window state on window initialization. You can then choose to use the `ToggleOnTop` Command to remove the Window State so that it is behind the fullscreen window again.

**Comment by Eskaan** [comment]
I implemented it exectly like the old window sorting for now, this should be ready for review.

**Review by mautamu — APPROVED** [review]
Been testing this for a while in local and it appears to be working fine. Looks good from a code perspective also; thanks Eskaan!

**Comment by Eskaan** [comment]
Two problems:
1. c9681f49c4d62471e6d8c44011c49aff5d58a3d6 The `WindowState::Above` solution wasn't really working: Only newly created windows would be affected and those would keep the `Above` state even when the parent went out of fullscreen.
2. 1c0700165b9ff3d2eba3fd73e35419efe52e704b The maximized windows were on the wrong layer.

**Pull request merged**
