### PR TITLE
Support 32bit archs

### PR DESCRIPTION
**Pull request by AethanFoot**
This allow leftwm to compile on 32 bit architectures in response to #389 and #404. Hopefully this works (I can only test with i686-unknown-linux-gnu). If arm builds are still failing the solutions I have found (but can't test) is to make sure the correct linker is set (I would of thought it is when being built on that given architecture), these are at https://github.com/rust-lang/rust/issues/28924.
Thanks.

### CODE REVIEW

**Comment by mautamu** [comment]
Can confirm that this builds on i686/Rust 1.53.0 now, and tests pass. 

For posterity's sake, if you get signal 9 error, you need to add additional RAM or Swap:
```
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.
```

```
$ uname -a
Linux arch 5.12.6-arch1-1.0 #1 SMP PREEMPT Mon, 24 May 2021 07:10:25 +0000 i686 GNU/Linux

$ rustup show
Default host: i686-unknown-linux-gnu
rustup home:  /home/user/.rustup

stable-i686-unknown-linux-gnu (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

Will look into whether or not ARM builds pass now a bit later.

**Comment by ReneganRonin** [comment]
Hello. May I ask to get the patch files so I can test this on arm on leftwm-0.2.7 through cross compiling from `xbps-src` in voidlinux? if it is fine with you. thanks ☺️

**Comment by Phate6660** [comment]
Not OP, but you can get a patch by appending `.patch` to a PR URL.
Like so: https://github.com/leftwm/leftwm/pull/405.patch

**Comment by ReneganRonin** [comment]
yeah thanks. i did not know that exists xD

**Comment by Phate6660** [comment]
I know right? The only reason I knew about it is because I came across some
random blog post talking about cool features Github have / Github users have made.

**Comment by ReneganRonin** [comment]
going to test the patch now if it fixes the build issues. i will update later the results if i have time :3

**Comment by VuiMuich** [comment]
I usually use something like this (though I have to look up the correct command eeevery time, I don't know, why I can't memorize this..
```
git pull upstream pull/405/head:32bit-support
git switch 32bit-support
```

> seems like this patch is 0.2.8 unreleased. i guess i will have to wait for 0.2.8

:thinking: if you are on the latest git, this is basically 0.2.8. 0.2.7 is just the latest released bin.

**Comment by ReneganRonin** [comment]
> I usually use something like this (though I have to look up the correct command eeevery time, I don't know, why I can't memorize this..
> 
> ```
> 
> git pull upstream pull/405/head:32bit-support
> 
> git switch 32bit-support
> 
> ```
> 
> 
> 
> > seems like this patch is 0.2.8 unreleased. i guess i will have to wait for 0.2.8
> 
> 
> 
> :thinking: if you are on the latest git, this is basically 0.2.8. 0.2.7 should just be the latest released bin.

yep. but Void Linux's void-packages i think wants the released version for verifying checksums, not sure tho but i play safe so i chose the released version. 😄

**Comment by VuiMuich** [comment]
I see, makes sense.
Maybe we can have a bump to 0.2.8 when 405 gets merged.

@lex148 would you like to have some specific issues solved before 0.2.8?

**Comment by AethanFoot** [comment]
> I see, makes sense.
> Maybe we can have a bump to 0.2.8 when 405 gets merged.
> 
> @lex148 would you like to have some specific issues solved before 0.2.8?

I was going to make an issue about this today, I think we should test the 32 bit changes a day or two. In terms of issues to be done i would say #353 and #352 should be done (i might have time later to do these), and any other issues related to current features. I think we should still open an issue for this as somewhere we can bring together the issues we think need completing.
Thanks.

**Comment by AethanFoot** [comment]
Opened a discussion at https://github.com/leftwm/leftwm/discussions/411.
Thanks.

**Comment by lex148** [comment]
I agree, its getting close to a time for another release. It would be nice to have those two, but I don't think it is mandatory. Lets shoot for Friday.

**Comment by ReneganRonin** [comment]
hello. i am testing https://github.com/leftwm/leftwm/archive/master.tar.gz in xbps-src if it can build with arm and i686. void wont accept it of course since it is a release version *yet* so i am doing it in my own local repository or fork. going to update soon if it built correctly. i cannot test it if it runs though.

**Comment by ReneganRonin** [comment]
Update: failed to build for  `i686` in `xbps-src`

```
Compiling leftwm v0.2.8 (/builddir/leftwm-master)
error[E0658]: use of unstable library feature 'unsigned_abs'
  --> src/models/tag.rs:46:27
   |
46 |             *mwp -= delta.unsigned_abs();
   |                           ^^^^^^^^^^^^
   |
   = note: see issue #74913 <https://github.com/rust-lang/rust/issues/74913> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `leftwm`

To learn more, run the command again with --verbose.
=> ERROR: leftwm-0.2.8_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
   Compiling liquid v0.22.0
   Compiling leftwm v0.2.8 (/builddir/leftwm-master)
error[E0658]: use of unstable library feature 'unsigned_abs'
  --> src/models/tag.rs:46:27
   |
46 |             *mwp -= delta.unsigned_abs();
   |                           ^^^^^^^^^^^^
   |
   = note: see issue #74913 <https://github.com/rust-lang/rust/issues/74913> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `leftwm`

To learn more, run the command again with --verbose.
=> ERROR: leftwm-0.2.8_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
   Compiling liquid v0.22.0
   Compiling leftwm v0.2.8 (/builddir/leftwm-master)
error[E0658]: use of unstable library feature 'unsigned_abs'
  --> src/models/tag.rs:46:27
   |
46 |             *mwp -= delta.unsigned_abs();
   |                           ^^^^^^^^^^^^
   |
   = note: see issue #74913 <https://github.com/rust-lang/rust/issues/74913> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `leftwm`

To learn more, run the command again with --verbose.
=> ERROR: leftwm-0.2.8_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

**Comment by AethanFoot** [comment]
@ReneganRonin rustup needs updating, ```rustup update```.
Thanks

**Pull request merged**
