### PR TITLE
Global up script

### LINKED ISSUE #362: [Feature] Global up script
Currently the only way to do setup or run custom programs in the background is to use the `~/.config/leftwm/theme/current/up` script. This is really inconvenient if you want to be able to switch between themes - you have to edit each theme's `up` script to do what you need.
I propose a global up script (`~/.config/leftwm/up`) which can remain the same while you switch between themes.

### PR DESCRIPTION
**Pull request by mfdorst**
This implements the change proposed in #362.

Closes #362.

### CODE REVIEW

**Comment by mautamu** [comment]
Tagging #292 as this would need to be considered therein.

**Comment by lex148** [comment]
So I don't have a problem with this if people want this feature, but why not just put what you want in `.config/autostart`

LeftWM respects the behavior of the autostart folder and boots everything in it only once at boot time.

**Comment by AethanFoot** [comment]
I feel it has its place, this is a common point I see often brought up (mostly as they dont know about autostart directory). However I feel for newer users it may be easier to setup through the wm, instead of having to additionally search how to use the autostart directory or .xprofile, etc.
If we feel this isnt entirely needed then we should add a bit to the wiki on these various methods of autostarting which are wm independent

**Comment by lex148** [comment]
I have no problem with adding this as well. I would just encourage people to use a more standard way if they can.

**Comment by VuiMuich** [comment]
Maybe we should add a 'getting started' section in the wiki where we help with common pitfalls when getting new into leftwm.

I'll propose something in the next days.

**Comment by mfdorst** [comment]
I looked into autostart but what I found seemed to indicate that it was part of Gnome. I see now on further inspection that it's not. Perhaps we could add a link to the autostart documentation somewhere in the README? I found this link ([arch wiki](https://wiki.archlinux.org/title/XDG_Autostart)), idk if there's a better resource for it.

**Comment by mfdorst** [comment]
Just a final two cents, I think that this has its own place even for people who are aware of and use `autostart`, because there may be things people want to run _only_ for `leftwm`, but not when using some other WM or DE. This will serve in that case.

**Comment by rigoletto-freebsd** [comment]
I think a middle ground and simpler solution would be something like i3: [exec and exec_always](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup). :-)

**Comment by mautamu** [comment]
> I think a middle ground and simpler solution would be something like i3: [exec and exec_always](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup). :-)

I'm trying to think of the best way to implement this. Perhaps one alternative is with #292 to have `Task`s in config.toml as well as theme.toml and add hooks for .up (theme), .down (theme), .start (leftwm), .end (leftwm), and .install (leftwm-theme).

**Pull request merged**
