### PR TITLE
Even more clippy lints

### PR DESCRIPTION
**Pull request by mautamu**
Howdy,

To avoid a repeat of #263/#265, I'm trying these in smaller batches by lint category. This PR performs the Panic! documentation lint ~~(partially~~ complete ~~)~~, the needless_pass_by_value, and a few other minor lints. It also accidentally includes a reverted #165 as I was testing that and didn't realize what was up.

Best,
Mautamu

### CODE REVIEW

**Comment by lex148** [comment]
code cleanup is so nice :)

**Comment by lex148** [comment]
So I have been testing and all looks good, but it has a conflict with master. If you get this resolved I will merge.

**Comment by mautamu** [comment]
It would be great if someone who has some time would give this a good test. I caught one regression that's now fixed, but there might be more.

**Comment by mautamu** [comment]
# Clippy lints:
Ignored:
- must_use_candidate
- precision_loss
- cast_possible_truncation
- cast_possible_wrap
- cast_sign_loss
- mut_mut

```cargo clippy -- -W clippy::pedantic -A clippy::must_use_candidate -A clippy::cast_precision_loss -A clippy::cast_possible_truncation -A clippy::cast_possible_wrap -A clippy::cast_sign_loss -A clippy::mut_mut```

With this, the last two major issues to address are:
```
warning: this function has too many lines (149/100)
   --> src/display_servers/xlib_display_server/event_translate.rs:16:5
...
warning: this function has too many lines (441/100)
   --> src/handlers/command_handler.rs:15:1
```

See #269 for the discussion on `command_handler`.

**Pull request merged**
