### PR TITLE
Remove Chrono Dependency

### PR DESCRIPTION
**Pull request by mautamu**
Partially resolves RUSTSEC2020-0159.
 - Removes chrono 
 - Bumps time. 

 !!!DOES NOT REMOVE TIME 0.1.43 FROM ENTIRE DEPENDENCY TREE!!!

Cheers,
Mau

Tagging #594,

### CODE REVIEW

**Comment by mautamu** [comment]
I haven't been able to locally check this for accuracy. @0323pin Does this work for you?

(MSRV check blocked on https://github.com/leftwm/leftwm/pull/694).

**Comment by 0323pin** [comment]
@mautamu It was sleep time where I am. Thanks for the quick work.
I need to get a few things done first (work) but, I'll kick a patched build as soon as I possibly can and report back.
Thanks you!

**Comment by VuiMuich** [comment]
May I ask why you are using `UTC` in the `log` and `local` in `leftwm-state`?

Btw. nice one with the `if let Ok(..)` I only found `.expect()` to unwrap it in my commit on #508 yesterday.

**Comment by 0323pin** [comment]
@mautamu It builds fine but I get "TIME ERROR!" on the bar when having `{{ localtime }}` in `template.liquid`.
Should I be calling something else in `template.liquid`? I've looked at the changes but, I'm failing to see

If I use `{{ "now" | date: "%Y-%m-%d %H:%M" }}` time shows up in UTC as expected.

**Comment by VuiMuich** [comment]
> @mautamu It builds fine but I get "TIME ERROR!" on the bar when having `{{ localtime }}` in `template.liquid`. Should I be calling something else in `template.liquid`? I've looked at the changes but, I'm failing to see how to call the new variable.
> 
> If I use `{{ "now" | date: "%Y-%m-%d %H:%M" }}` time shows up in UTC as expected.

`{{ "now" | date: "%Y-%m-%d %H:%M" }}` is 'a function' directly from the `liquid-core` crate and is only able to return UTC

This is weird, the following code works fine in the `fn setup_logfile()` but returns an error just as mautamu's code:
```rust
    let date = time::OffsetDateTime::now_local().expect("Localtime: ");
    return date
        .format(time::macros::format_description!(
            "[year]-[month]-[day] [hour]:[minute]"
        ))
        .expect("Formated localtime: ")
        .to_string();
```

**Comment by 0323pin** [comment]
> `{{ "now" | date: "%Y-%m-%d %H:%M" }}` is 'a function' directly from the liquid-core crate and is only able to return UTC

Yes, I know. You have linked the bug earlier.

So, you're seeing it also?

**Comment by VuiMuich** [comment]
I built this little test project:
`src/main.rs`
```rust
fn get_localtime() -> String {
    // let now = chrono::Local::now();
    // now.format("%m/%d/%Y %l:%M %p").to_string()

    // log::info!("The `{{ localtime }}` feature is deprecated, please use another source like this little program from the epitaph theme https://github.com/VentGrey/Epitaph/blob/90a4a799001d8896beff5226143dddaf34e9b3f4/scripts/lemonbar/time.c");
    // "DEPRECATED_LOCALTIME".to_string()

    let now = time::OffsetDateTime::now_local().expect("My Localtime");
    return format!(
        "{}",
        now.format(time::macros::format_description!(
            "[year]-[month]-[day] [hour]:[minute]"
        ))
        .expect("My Formated localtime")
    );

    // if let Ok(now) = time::OffsetDateTime::now_local() {
    //     if let Ok(ret) = now.format(time::macros::format_description!(
    //         "[month]/[day]/[year] [hour]:[minute]:[second]"
    //     )) {
    //         return ret;
    //     }
    // }
    // String::from("TIME ERROR!")
}
```
`Cargo.toml`
```toml
[package]
name = "timetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = {version = "0.3.7", features = ["formatting", "local-offset", "macros"]}
```
And it runs as expected:
```shell
timetest >>> cargo r
   Compiling timetest v0.1.0 (/home/vuimuich/timetest)
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
     Running `target/debug/timetest`
The one: 202202071212
and the other: 2022-02-07 12:12
```
So something seems to be weird in the context of `leftwm-state`. Maybe it is from conflcting `time` crates, as `liguid-core` uses `0.1.44` and we want `0.3.7`...

**Comment by 0323pin** [comment]
> So something seems to be weird in the context of leftwm-state. Maybe it is from conflcting time crates, as liguid-core uses 0.1.44 and we want 0.3.7...

Indeed, it's strange. The code runs as expected when used stand-alone but fails when inside `leftwm-state`.
Maybe it's worthy to try to force `liquid-core` to update `time`, if it turns out to be conflicting crate versions?

**Comment by VuiMuich** [comment]
But actually that would also be weird, as `liquid` only gets used locally in functions and I thought that should limit its life span and 'our' `time` is also limited to the `get_localtime` function.
And why is my variant calling `get_localtime` even with `{{ "now" | date: "%Y-%m-%d %H:%M" }}`?

**Comment by 0323pin** [comment]
> And why is my variant calling get_localtime even with {{ "now" | date: "%Y-%m-%d %H:%M" }}?

You're right, that's weird. This should be a liquid only thing and shouldn't be impacted. 😮

**Comment by mautamu** [comment]
> May I ask why you are using `UTC` in the `log` and `local` in `leftwm-state`?
> 

That’s just the fallback, since now_local returns Result and now_utc returns the underlying object without a result.


Also that’s some extremely peculiar behavior  we’ve found… 🤨. I’ll try to take a look after work if y’all haven’t figured it out by then.

Also just saw the work on the logger default 🤦. Apologies I didn’t see it earlier. Will try to integrate proposed changes later too.

**Comment by VuiMuich** [comment]
> That’s just the fallback, since now_local returns Result and now_utc returns the underlying object without a result.

:see_no_evil: I totally missed that it is in the `else` arm, now that absolutely makes sense as a fallback. Sorry for my blindness :bow:

> Also that’s some extremely peculiar behavior we’ve found… raised_eyebrow. I’ll try to take a look after work if y’all haven’t figured it out by then.
> 
> Also just saw the work on the logger default facepalm. Apologies I didn’t see it earlier. Will try to integrate proposed changes later too.

I tried to backtrace it but I am bad at this and don't understand the output :roll_eyes: 
I asked for an opinion on the rust discord and they think it is not possible to compile two versions of a crate into one binary, which is a pitty, as `chrono` is used as well in `liquid-core` as mentioned and in `slog-term`.
Right now I am tumbling down that rabbit whole:
- `liquid` are aware of the vulnerability and appear generally open to do the move to `time` – no idea though how big that effort would be for them
- `slog-term` have no (relevant) mention of `chrono` or `time` or the vulnerability, but as this is the only crate of the `slog` suite chances are the changes to do the switch are manageable
- `chrono` appears to be almost completely stalled (last commit in October 2021) at this point

**Comment by 0323pin** [comment]
> I asked for an opinion on the rust discord and they think it is not possible to compile two versions of a crate into one binary

:(

> solved this by `slog-term v2.8.1`

Nice, they just need to push a release now.

Which, leaves `liquid`.

**Comment by mautamu** [comment]
Oh actually I think I have an idea for how to do it, but it’ll take a bit of effort. 

The tldr is this:

https://stackoverflow.com/questions/50999616/how-to-idiomatically-alias-a-crate-in-rust-2018

**Comment by VuiMuich** [comment]
Another idea: as `leftwm-state` operates on updates on the state we could store the time in the state file and update it from the `worker`, so the two `time` crates end up in different binaries.

**Comment by 0323pin** [comment]
Hmm... sounds like a burden to maintain. Much cleaner if `liquid` and `slog-term` could keep `time` in sync.

Thoughts?!

**Comment by VuiMuich** [comment]
:thinking: so 

> Oh actually I think I have an idea for how to do it, but it’ll take a bit of effort.
> 
> The tldr is this:
> 
> https://stackoverflow.com/questions/50999616/how-to-idiomatically-alias-a-crate-in-rust-2018

I tried this in the little `timetest` from above, but I believe it breaks macros :sob:

**Comment by mautamu** [comment]
Ah there’s a way to do it without macros but will make the code less clean 😢.

**Comment by mautamu** [comment]
I've gotten a bit further, but my solution can't obtain the current offset. We could pass through an offset? Not super familiar with liquid, but maybe localtime(-5)? 

Thoughts? @VuiMuich / @0323pin

**Comment by 0323pin** [comment]
> I've gotten a bit further, but my solution can't obtain the current offset. We could pass through an offset?

Do you mean it passes UTC?
Because `liquid` can do that on it's own. I also thought about adding one to the hour but couldn't find how to do that in `liquid`.
Unfortunately, `liquid` doesn't seem to do `date -d '+1 hour'

**Comment by mautamu** [comment]
I think this is what's causing #275

**Comment by 0323pin** [comment]
> I'm now in favor of dropping chrono and time from leftwm-state entirely.

Looks like `liquid` is closing in on a fix to drop `chrono`, https://github.com/cobalt-org/liquid-rust/pull/460

**Comment by VuiMuich** [comment]
> > I'm now in favor of dropping chrono and time from leftwm-state entirely.
> 
> Looks like `liquid` is closing in on a fix to drop `chrono`, [cobalt-org/liquid-rust#460](https://github.com/cobalt-org/liquid-rust/pull/460)

If they get the crate bumped as soon as they merged this I guess we could wait and bump `liquid` in our `Cargo.toml` as well.

**Pull request closed without merging**
