### PR TITLE
monocle Layout

### PR DESCRIPTION
**Pull request by VuiMuich**
As proposed in #174 here is my attempt to add a simple Monocle Layout, which sets the primary window to full screen and hides any others. The windows can be cycled through with MoveWindow commands.

In a hacky way it get rid of the margin, but I am not sure how to handle properly to return to the theme margin again in other layouts, yet.

Also it would be possibly nice to have a monocle specific margin, like doule or tripple the theme margin. Maybe have a "monocle-factor" value in the theme.toml?

### CODE REVIEW

**Comment by AethanFoot** [comment]
Not sure if anyone agrees but I feel this layout should respect margins, with a separate feature that allows the user to completely fullscreen any application (not respect margins and hide the bar). Like you can with a browser with pressing F11 and keep the current layout so when you leave fullscreen everything is the same.

**Comment by AethanFoot** [comment]
I have all found this issue, not sure mechanism is not working nicely, but any window added past the initial window covers my monitor starting at +0+0 (not matter which screen im on).
Video:
https://user-images.githubusercontent.com/63980259/108344507-1f2dcc80-71d5-11eb-90fb-a9683981c383.mp4

**Comment by VuiMuich** [comment]
> I have all found this issue, not sure mechanism is not working nicely, but any window added past the initial window covers my monitor starting at +0+0 (not matter which screen im on).

Thanks for the catch. I think I hav an idea, why this is happening. The layout so far does not handle how new windows are created.
New windows are usually just appended to the existing ones but whte monocle layout should put new windows as primary. 
Also (and maybed related) focus switching is kind of inconistent.

Maybe it would be better to make this layout more dependent on the focus state of windows anyway. I try if I can make it work this way.

I agree that a proper fullscreen mode for windows is kind of a must have and should be independent. Though on top of that I think the monocle should have a margin setting that stands out of the usual layouts margins, thus my suggestion with the margin-factor in theme.toml

**Comment by VuiMuich** [comment]
The last commit is somewhat working.
As mentioned I am looking for a way to get the layout dependent on the focus-state, but currently I'm somewhat struggeling to get the focused window returned to my update function.

The Idea is to iterate over all windows of the workspace, and set the size, then match the iter-item with the window that has focus to set its visibility true, all other windows to false.

I am uncertain though if this way the layout update get called automatically if focus changes, or if dedicated action is needed.

Maybe someone with better rust-fu could help me out (esp. on how to properly get the current focuesd window.)

**Comment by VuiMuich** [comment]
with mautamu's helpful PR on my fork I think it is ready to leaf the WIP state for now.

It's still not perfect, but ready for general use I'd say.
How the margins are handled should be in a dedicated PR anyways, imo

**Pull request merged**
