### PR TITLE
Rename `theme` to `example`

### PR DESCRIPTION
**Pull request by VuiMuich**
Since more and more interesting ideas beyond pure themeing get discussed on our discord server, like rofi layout switcher, dmenu powermenu (i believe this one was actually mentioned in some issue (gonna reference later) etc. it would be great to have a central space to gather such niceties as examples.

### CODE REVIEW

**Comment by VentGrey** [comment]
Im willing to get some examples on the lemonbar / dmenu part if needed :)

**Comment by hertg** [comment]
Hmm, while I actually like the idea of doing that, maybe it's better if we move the examples (and community-scripts?) to a separate repository? It would be kinda nice if those were easily accessible within this repository, but I think that moving them to a separate repository would make sense because then they wouldn't "interfere" with the main LeftWM repo. 
Not that contributions to the `examples` folder necessarily interfere with the source code itself, but from the standpoint of managing Github Issues/PRs it does. What do you think about that?
We could still add the repository as submodule in the main leftwm repo so it's easier to find on Github.

**Comment by VentGrey** [comment]
That would make sense. Usually, some projects come have a "contrib" part (`leftwm-contrib`?) which is just a compilation of community tools for the main project.

**Comment by VuiMuich** [comment]
So, now that we have leftwm/leftwm-contrib, the question is, are we ready to have this as a submodule, or would we want/need something else for the `examples` directory..

**Comment by VuiMuich** [comment]
I don't get what's conflicting here :thinking:

**Comment by VentGrey** [comment]
I cannot see anything in the conflict message. Is it dangerous to try a recursive merge strategy? Like `Xours` or `Xtheirs`?

**Comment by VuiMuich** [comment]
I am gonna close this. The various troubles with the community themes being managed as submodules dampened my enthusiasm for this idea.
We have the `leftwm-contrib` repo now, though. So I am going to mention this in the README. Updates to the basic themes are sparse enough to be bothered to get synced manually...

**Pull request closed without merging**
