### PR TITLE
Add SetLayout Command

### PR DESCRIPTION
**Pull request by nickzana**
As discussed in #174.

### CODE REVIEW

**Comment by lex148** [comment]
@nickzana This is great thanks for the PR. I'm definitely adding a couple set commands to my config. Would you consider updating the external commands to support these as well? If you do that people can add shortcuts in their Polybar configs.

**Comment by nickzana** [comment]
Sorry about the oversight, I haven't configured anything with `ExternalCommand`s before so I didn't realize that was something I could add. Gave it my best shot in #253.

**Comment by nickzana** [comment]
Also, I wasn't able to figure out how to make a PR to the Wiki, but we should probably add documentation for the `SetLayout` command there as well.

**Comment by mautamu** [comment]
@nickzana if you PR it against mautamu/leftwm_wiki we can prolly pop that over here.

**Comment by mautamu** [comment]
@lex148 is it alright if I move ownership of mautamu/leftwm_wiki to the leftwm organization?

**Comment by nickzana** [comment]
Ok @mautamu, made the PR on mautamu/leftwm_wiki. First time contributing to a GitHub Wiki, sorry if my convention's a bit off.

**Pull request merged**
