### PR TITLE
Fix for #154

### LINKED ISSUE #154: Weird startup banners: Libreoffice, gimp, krita, cura, etc.
### Description

Programs like the ones listed in the title show a banner at startup. They are displayed "funnily". For instance:
image

In the case of krita or cura the banner is showed in the left corner.

### Expected behavior

I believe a good default would be to have these type of "banners" displayed floating at the center. I think other tiling WMs do it without user intervention, but I don't know if they are hardcoded somehow or there is some information that the WM can use to recognise these types of windows.

### PR DESCRIPTION
**Pull request by mautamu**
Howdy,

This partially fixes #154 , but still does not properly size Splash screens. Only tested on LibreOffice 7.0.4-1, would be helpful to see if it also fixes gimp, cura, and krita.

To finish this, we'd need to know how to get the window height and width requested by the program and apply it.

Best,
Mautamu

### CODE REVIEW

**Comment by lex148** [comment]
Hey @mautamu awesome work as always. You have jumped into the deep end with this one... 
So my understanding is the requested sizing **should** be send to us  in a `XA_WM_NORMAL_HINTS` or a `XA_WM_HINTS` however It has never quite worked right. 

Take a look at [event_translate_property_notify.rs](https://github.com/leftwm/leftwm/blob/master/src/display_servers/xlib_display_server/event_translate_property_notify.rs)
The purpose of this file is to take in PropertyNotify Events and assign them into meaningful actions within LeftWM 

I will take a look too and see if I can't help identify why we aren't getting the correct sizing info requested from the window. Just a side note. I think this is why dialog boxes are sometimes oddly sized too.

**Comment by mautamu** [comment]
So it appears to follow the following route from event_translate_property_notify.rs over to window_handler.rs:
```rust
//src/window_handler.rs
    Window {
        handle: XlibHandle(39845889),
        transient: None,
        visible: false,
        is_floating: false,
        floating: None,
        never_focus: false,
        debugging: false,
        name: Some("LibreOffice"),
        type_: Splash,
        tags: ["alpha"],
        border: 1,
        margin: 10,
        states: [],
        normal: XYHW {
            x: 0,
            y: 0,
            h: 5,
            w: 5,
            minw: 5,
            maxw: 999999999,
            minh: 5,
            maxh: 999999999,
        },
        start_loc: None,
        strut: None,
    }; //Received by LeftWM

//src/display_servers/xlib_display_server/xwrap.rs

    let attrs = XWindowAttributes {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        border_width: 0,
        depth: 24,
        visual: 0x55754e048b68,
        root: 415,
        class: 1,
        bit_gravity: 1,
        win_gravity: 1,
        backing_store: 0,
        backing_planes: 4294967295,
        backing_pixel: 0,
        save_under: 0,
        colormap: 44040194,
        map_installed: 0,
        map_state: 0,
        all_event_masks: 6520848,
        your_event_mask: 6422544,
        do_not_propagate_mask: 0,
        override_redirect: 0,
        screen: 0x55754e033380,
    } // as managed by LeftWM

//src/window_handler.rs


   Window {
        handle: XlibHandle(39845889),
        transient: None,
        visible: false,
        is_floating: true,
        floating: Some(XYHW {
            x: 0,
            y: 0,
            h: 0,
            w: 0,
            minw: -999999999,
            maxw: 999999999,
            minh: -999999999,
            maxh: 999999999,
        }),
        never_focus: false,
        debugging: false,
        name: Some("LibreOffice"),
        type_: Splash,
        tags: ["alpha"],
        border: 1,
        margin: 10,
        states: [],
        normal: XYHW {
            x: 0,
            y: 0,
            h: 480,
            w: 290,
            minw: 5,
            maxw: 99999,
            minh: 5,
            maxh: 99999,
        },
        start_loc: None,
        strut: None,
    }; // set by LeftWM
```

Manually trying to set the normal: XYHW to 0,0,480,290 in the window_handler.rs results in the full screen effect again, but shifted down half the window.

**Comment by mautamu** [comment]
I believe I found which variables need to be requested and obeyed by LeftWM:
```
(gimp)
  Normal window size hints:
      Program supplied location: 0, 0
      Program supplied minimum size: 962 by 562
      Program supplied maximum size: 962 by 562
      Program supplied window gravity: NorthWestGravity
  No zoom window size hints defined
```

```
(LibreOffice)
  Normal window size hints:
      Program supplied location: 0, 0
      Program supplied size: 644 by 199
      Program supplied minimum size: 644 by 199
      Program supplied maximum size: 644 by 199
  No zoom window size hints defined
```




Interestingly Gimp and LO both resize to the same dimms:
```
xwininfo: Window id: 0xa00001 "LibreOffice"

  Root window id: 0x19f (the root window) (has no name)
  Parent window id: 0x19f (the root window) (has no name)
     0 children.

  Absolute upper-left X:  480
  Absolute upper-left Y:  290
  Relative upper-left X:  480
  Relative upper-left Y:  290
  Width: 960
  Height: 526
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +480+290  -480+290  -480-264  +480-264
  -geometry 960x526+480+290
```
and
```
xwininfo: Window id: 0x3e00003 "GIMP Startup"

  Root window id: 0x19f (the root window) (has no name)
  Parent window id: 0x19f (the root window) (has no name)
     1 child:
     0x3e00004 (has no name): ()  1x1+-1+-1  +479+289

  Absolute upper-left X:  480
  Absolute upper-left Y:  290
  Relative upper-left X:  480
  Relative upper-left Y:  290
  Width: 960
  Height: 526
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +480+290  -480+290  -480-264  +480-264
  -geometry 960x526+480+290
```


With this information, I believe we may be able to fix this issue in the near future. I am working on a patch that works.

The big thing is getting the information from [this](https://github.com/leftwm/leftwm/blob/e56d49f671503759aae4dc59e8572b15e29f7eda/src/display_servers/xlib_display_server/xwrap.rs#L1161) Xwrap function. We may need to also finish the "todo" listed therein.e

**Comment by mautamu** [comment]
Partially_working_Leftwm_LO
Finally got it mostly working. Just need to figure out how to center the window and clean up the code.

(Border artifact is the new window being painted, LibreOffice starts up too quick now!)

**Comment by mautamu** [comment]
I am happy to announce that this is now complete!

Screenshot_2021-03-20_01-30-20

**Comment by lex148** [comment]
@mautamu you are amazing

**Pull request merged**
