### PR TITLE
feat(layout) center main

### PR DESCRIPTION
**Pull request by uipoet**
I have a super ultrawide monitor (5120x1440) where the splitting down the center has one looking far left or right at the primary window. By centering the primary window splitting the remaining windows left and right a nice balance is experienced.

### CODE REVIEW

**Comment by lex148** [comment]
This is really nice. I think its my new favorite layout.

**Comment by uipoet** [comment]
Glad you like it. Is there already a way we can target our favorite layouts with key bindings or does that need implementing?

**Comment by lex148** [comment]
No that would need to be added. LeftWM does have a pipe file to receive external commands. This is how most external bars interact with it. I would want to support it through this mechanism. If you add a ticket I will work in this. or if you would like to take a stab check out:
https://github.com/leftwm/leftwm/blob/master/src/handlers/external_command_handler.rs

**Comment by uipoet** [comment]
Cool. Yes, I'll have a look and PR if I can or punt to an issue if not.

**Pull request merged**
