### PR TITLE
[CONFIG BREAKING DRAFT] Begin implementing #201, #260, #270, #329

### PR DESCRIPTION
**Pull request by mautamu**
Howdy,

This PR can serve as a tracking issue for #201, #260, #270, and related configuration issues. As mentioned in #270, we will likely want to increment LeftWM to 0.3.0, as the changes posed in the linked issues will likely require some changes to theme and user configurations. While 15edd1a does not require such changes, once fully implemented those changes will change the overall flow of LeftWM such that changes are warranted. Here is the new theme.toml specification, with slightly modifications from #201 

```toml
border_width = 4 # define these up here for backwards compatibility with leftwm < 0.2.7
margin = [10, 10]
default_border_color = "#1E272B"
floating_border_color = "#1E272B"
focused_border_color = "#78824B"

name = "mytheme" # The name of the theme, MUST be set
description = "A basic theme" # A basic description, such as "A brown and orange theme inspired by sunflowers"
repository = "https://github.com/mautamu/theme" # The git repository for the theme. 
# Optional but requires commit if included. 
#Commit may be "*", but "*" may be rejected by maintainers for security purposes.
commit = "*" # pin at a specific version as a "release"
version = "1.0.0" # SEMVER-compatible version for the THEME
leftwm_versions = ">2.6.7" # SEMVER-compatible leftwm versions
dependencies = ["polybar", "dunst"]  # Used to check if required packages are installed in the system, internally calls is_in_path(dependency[i]) 

# task.program_name.up sets up the program. The following section will spawn `polybar mybar`
[task.polybar.up]
command = "polybar" # if command is not set, will default to program_name
# NOTE: do not include anything other than /path/to/program_name or program_name
# Everything else MUST go in arguments or else your task will not be called.
args = ["mybar"]

# defaults to pkill program name if no down script is provided.
[task.polybar.down]
command = "killall"
args = ["-q", "polybar"]

# if program_name in task.program_name.{up,down} does not match any dependency listed, a command value must be provided.
# paths are relative to the current directory of theme.toml file.
[task.notification.up]
command = "/usr/bin/dunst"
args = ["--config", "configs/dunstrc"]

[task.polybar.new_window]
packages = {pacman = ["polybar"], apt =["polybar"], dnf = ["polybar"] }

[task.polybar.install]
packages = {pacman = ["polybar"], apt =["polybar"], dnf = ["polybar"] }

[task.action_name.post_install]
command = "killall"
args = ["-q", "polybar"]

[task.action_name.pre_install]
command = "killall"
args = ["-q", "polybar"]
```
```

CHANGES: 
2021-05-07: removed [global]

### CODE REVIEW

**Comment by VuiMuich** [comment]
I like this a lot!
As this draft so far is more on the theme side, would you like to keep some more config related ideas in a separate thread, or do we gather all (possibly) breaking changes here?

Some ideas circle around config options for commands, or custom defaults for window/tag/workspace behaviour.

**Comment by mautamu** [comment]
@VuiMuich I think we can keep track of them here, but add as separate PRs. A lot of these changes are a interwoven/interdependent so it might be best just to merge them into this PR.

**Comment by mautamu** [comment]
I'm working right now on putting everything behind a `cargo build --release --features unstable` option so that we can merge this now, work until everything's ready, and then remove the feature gate for 0.3.0.

**Comment by mautamu** [comment]
Specifically tagging @AethanFoot and @lex148  to look over this one. I have moved everything behind the `unstable` feature gate so that this can get merged into master.

Some of the requisite functions to actually implement the new configuration options have not been added to this PR, but this PR does make for one larger breaking change to be tested and built out before the feature gate is removed (and would likely push us toward 0.3.0). 

Best,
Mautamu

**Comment by AethanFoot** [comment]
Looking over on my phone it looks good, once this is merged I think it would be useful to create a pinned issue where we can list anything we are considering adding to this release. Which would make it easier for anyone who wants to contribute. 
Awesome work, Thanks!

**Comment by VuiMuich** [comment]
As I was working on #460 I noticed once again, that the external commands are a bit awkward when used with args, as they require command and args to be quoted into a string, like `leftwm-command "SetLayout Monocle"`.
It would be nice if the quotations are not needed.
This should be possible with `clap`, right?
Since this change definitely would break how themes get loaded in the up script, I believe this change would belong here.

Whats others opinion on this?

**Comment by mautamu** [comment]
I believe so; it’s subcommands. If we want to do that it sounds pretty good to me

**Comment by mautamu** [comment]
@mautamu to fix:
If we only use it for this, why wouldn't we expose GotoTag (btw: @mautam can we fix this typo inconsistency in #292 please so it is GoToTag as all other To anywhere?) to the command_pipe?

**Comment by mautamu** [comment]
Should add pre- and post- install hooks to theme.toml

**Comment by mautamu** [comment]
Not sure that this is exactly needed any longer with all the changes we've already made config-wise. If we want to re-open this with reduced scope, e.g. to move away from `up`/`down` scripts I think that could be appropriate, just let me know!

**Comment by VuiMuich** [comment]
It is a bit sad to say good bye to #292 the old pal :cry:
The history of merged references is nice though :smiling_face_with_tear:

**Pull request closed without merging**
