### PR TITLE
clap version bumped up

### PR DESCRIPTION
**Pull request by TornaxO7**
# Description

bumped up the version of `clap` and fixed the suggestions from clippy.

Fixes #(issue)
No issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ x] Dependency updating

## Updated user documentation:

No need to do this.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test` locally with no errors or warnings reported
- [x] Enhanced review is performed with `cargo clippy -- -W clippy::pedantic -A clippy::must_use_candidate -A clippy::cast_precision_loss -A clippy::cast_possible_truncation -A clippy::cast_possible_wrap -A clippy::cast_sign_loss -A clippy::mut_mut`
- [x] Manual page has been updated accordingly
- [x] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by AethanFoot** [comment]
Looks good!

**Comment by VuiMuich** [comment]
Just one little question:
what is the `once_cell` dependency for?

**Comment by TornaxO7** [comment]
I added the [`command!()`](https://docs.rs/clap/3.2.12/clap/macro.command.html) macro in the code. As the docs says:
> Available on crate feature cargo only.

we need to enable the `cargo` feature of clap.

According to the [feature list](https://docs.rs/crate/clap/3.2.12/features) the `cargo` feature needs `once_cell`. When I didn't added it to the `Cargo.toml` file, the rust compiler was shouting at me, that there's a version conflict with `once_cell` and it suggested me to add the version of it to solve this. So I just added it to the `Cargo.toml` file and since then the rust compiler didn't complain anymore.

**Comment by VuiMuich** [comment]
Ah, I see. The addition of the macro is actually in #788, right?

**Comment by VuiMuich** [comment]
np, thanks for coearing that up

**Pull request merged**
