### PR TITLE
Chore: Update dependencies, bump MSRV

### PR DESCRIPTION
**Pull request by mautamu**
# Description

This commit updates all dependencies, resolves new clippy lint errors, and bumps the minimum MSRV to 1.65.0

## Type of change

- [x] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

## Updated user documentation:
MSRV is now 1.65.0

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not neccesary.
- [ ] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Review by Eskaan — CHANGES_REQUESTED** [review]
Is it really necessary to mark all those functions and structs as `pub(crate)`? I know they may not be used anywhere else but does clippy enforce that?

~~Also, I think the `let Some(...) = ... else {...}` wasn't introduced in this but the version before. Can't we set the MSRV to this version?~~ My fault, this is the correct version.

**Comment by mautamu** [comment]
> ~Also, I think the `let Some(...) = ... else {...}` wasn't introduced in this but the version before. Can't we set the MSRV to this version?~ My fault, this is the correct version.

Haha, I thought that too, hence why it took five commits to get that right.

> Is it really necessary to mark all those functions and structs as pub(crate)? I know they may not be used anywhere else but does clippy enforce that?

I'm not entirely sure, the GitHub Action Clippy and my local copy appear to disagree on whether this is necessary, but I didn't dig much further. Fwiw I think that these should be pub not pub(crate); do we want to bypass the lint on those files?

**Comment by Eskaan** [comment]
If your local clippy disagrees, I assume you have stable rust instead of v1.65.0?

I will take a look myself later today at what exactly may cause clippy to recommend `pub(crate)`.

**Comment by mautamu** [comment]
Yep! 
``` installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.65.0-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.69.0-nightly (44cfafe2f 2023-03-03)
```

Curiously it missed a few `let _ = function()`s, but I went in and reversed all of the `pub(crate)` annotations.

**Review by VuiMuich — APPROVED** [review]

**Comment by hertg** [comment]
lol, I just yesterday did basically the same work you did here because I missed this PR.
I'm gonna merge this soon if that's ok, and then after that do a PR I prepared that makes use of reusable workflows for the CI.

**Pull request merged**
