### PR TITLE
Workspace selection for window placement

### LINKED ISSUE #781: New window opens in workspace with mouse, not focus
**Describe the bug**
When opening a new window like the terminal or the browser through a keybind using `"Execute"`, it appears in the workspace (monitor in my case) on which the mouse is located, even if the focus is in another workspace.

I believe that the desired behavior would be for the new window to open in workspace which has focus, but correct me if I'm wrong.

**To Reproduce**
1. With a multi workspace and `sloppy_mouse_follows_focus = false` setup:
2. Move the mouse to workspace `A`
3. Move focus to workspace `B`
4. Spawn new terminal through keybind
5. Terminal spawns in workspace `A`

**Expected behavior**
New windows should spawn in the workspace with focus, not with the mouse.

**Environment:**
 - Distro: Arch
 - leftwm-check:
```sh
 $  leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 16b8a85
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Additional context**
Low priority

### PR DESCRIPTION
**Pull request by cyril-marpaud**
# Description

This PR introduces the new configuration option `create_follows_cursor: Option<bool>`.

New windows will follow:
- the cursor if set to `Some(true)`
- the focus if set to `Some(false)`
- the cursor in `Sloppy` mode / the focus in any other mode if set to `None` or unset

Fixes #781

## Type of change

- [ ] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [x] This change requires a documentation update

## Updated user documentation:

The [FocusBehaviour](https://github.com/leftwm/leftwm/wiki/Config#focus-behaviour) section of the documentation and man page should be updated accordingly with a paragraph resembling the description of this PR.

# Checklist:

- [x] Ran `make test-full` locally **BUT TESTS SEEM TO BE BROKEN**
- [x] Manual page has been updated accordingly
- [x] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Review by mautamu — APPROVED** [review]
Thank you again for this! While this looks good from a code perspective and basic single-monitor testing to me, I don't have a second monitor to test this out fully at the moment.

Perhaps @Pyxels can confirm whether this resolves the issue? If so, happy to merge! :)

**Comment by Pyxels** [comment]
Im sorry, I don't currently use Leftwm anymore and can't confirm.

**Comment by mautamu** [comment]
No worries, thanks Pyxels and thanks for the PR cyril-marpaud! Was able to test this locally and have made the necessary documentation changes, so will go ahead and merge this. :tada:

**Comment by 0323pin** [comment]
Shouldn't these new configuration options be added to the example [config.ron](https://github.com/leftwm/leftwm/blob/main/examples/config-with-comments.ron)?

**Comment by mautamu** [comment]
Thanks for the catch, @0323pin. Opened https://github.com/leftwm/leftwm/pull/1157 for that.

**Comment by 0323pin** [comment]
@mautamu I'm sorry to be that guy ... but, `reposition_cursor_on_resize` is still missing.

**Comment by mautamu** [comment]
No worries! Will wait to merge #1157 for a day or so to look over the config and make sure we're not missing anything more. Thanks @0323pin!

**Pull request merged**
