### PR TITLE
replace `<module-name>/mod.rs` with `<module-name>.rs`

### PR DESCRIPTION
**Pull request by VuiMuich**
# Description

This replaces any `<module-name>/mod.rs` with `<module-name>.rs` and the acompanying `<module-name>` directory.
I saw this recently in a bunch of other repos and thought this is nice.
I allways found it odd, to use the `mod.rs` way in most scenarios.

This is difinitelly a controversial PR and I am happy to follow the common oppinion, so please vote with :+1: :-1: if you like or dislike.

## Type of change

- [x] Development change (no change visible to user)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

## Updated user documentation:

Please insert user documentation that should be updated (as in the wiki).

See [CONTRIBUTING.md User Documentation section](../CONTRIBUTING.md#user-documentation) for further details.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not neccesary.
- [ ] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Review by Eskaan — CHANGES_REQUESTED** [review]
@VuiMuich I think you forgot to remove the testing code from the openbsd issue.
Edit: And some (seemingly finished but unmentioned) code to fix newline behavior of leftwm-state.

**Comment by VuiMuich** [comment]
Oh, me stupid:
```sh
leftwm >>> git status
On branch replace_modrs
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    display-servers/xlib-display-server/src/xwrap/mod.rs -> display-servers/xlib-display-server/src/xwrap.rs
	renamed:    leftwm-core/src/config/mod.rs -> leftwm-core/src/config.rs
	renamed:    leftwm-core/src/display_servers/mod.rs -> leftwm-core/src/display_servers.rs
	renamed:    leftwm-core/src/handlers/mod.rs -> leftwm-core/src/handlers.rs
	renamed:    leftwm-core/src/handlers/command_handler/mod.rs -> leftwm-core/src/handlers/command_handler.rs
	renamed:    leftwm-core/src/layouts/mod.rs -> leftwm-core/src/layouts.rs
	renamed:    leftwm-core/src/models/mod.rs -> leftwm-core/src/models.rs
	renamed:    leftwm-core/src/utils/mod.rs -> leftwm-core/src/utils.rs
	renamed:    leftwm/src/config/mod.rs -> leftwm/src/config.rs
	renamed:    leftwm/src/utils/mod.rs -> leftwm/src/utils.rs
	renamed:    leftwm/src/utils/log/mod.rs -> leftwm/src/utils/log.rs

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   leftwm/src/bin/leftwm-state.rs
	modified:   leftwm/src/bin/leftwm.rs

on  replace_modrs [$»!] via 🦀 v1.65.0
leftwm >>> git commit -am "replace `<module-name>/mod.rs` with `<module-name>.rs`"
```
:facepalm:

**Comment by VuiMuich** [comment]
> Only sense-full renames, CI completed with no errors. I think I can approve this without testing it locally. 

Thanks.
In general I was hoping for a little more expressions of opinions on this topic, but I guess this is an unanimous vote now 😝

**Comment by 0323pin** [comment]
@VuiMuich I like this, IMHO it makes it simpler.

**Comment by Eskaan** [comment]
@VuiMuich so I think this is a nice feature and should (only?) be used where it makes sense. For example if you have a folder containing a list of very similar modules the `mod.rs` should be moved out of it. On the other side if the `mod.rs` is part of the other files (for example the others contain utility functions for it) it should be in the same folder.
However I do not have a strong opinion on this in any way, I can easily work with it in any of those setups.

**Comment by VuiMuich** [comment]
> @VuiMuich so I think this is a nice feature and should (only?) be used where it makes sense. For example if you have a folder containing a list of very similar modules the `mod.rs` should be moved out of it. On the other side if the `mod.rs` is part of the other files (for example the others contain utility functions for it) it should be in the same folder. However I do not have a strong opinion on this in any way, I can easily work with it in any of those setups.

Woohoo, discussion!

I don't get yet, where you see the benefit of one over the other in both examples, tbh.

The benefit I see in the proposal is, that you can easly tab-complete the module name, and either go to the module itself, with `. + tab` or to the dir of submodules with `/ + tab` and the file tree also sorts neatly and IMO very consistently:
2022-12-22-092349_1232x1337_scrot

But I am happy to learn, why you have you preferences.

**Pull request merged**
