### PR TITLE
Fix and improve basic_lemonbar theme

### PR DESCRIPTION
**Pull request by simtd**
# Description

I fixed and improved the basic_lemonbar theme. The previous one didn't work for me because it was coded to only work for a multiple workspace setup. Now it should work for both one or multiple workspaces. 

New features or fixes:
- now works if user only has one workspace
- clock is independent of leftwm-state
- added clickable tags
- the status text not provided by leftwm-state only shows up on one instance of lemonbar
- added uname info
- changed lemonbar size slightly
- got rid of compositors
- better naming/syntax
- different theming

Fixes #(issue)

## Type of change

- [ ] Development change (no change visible to user)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by simtd** [comment]
I am working on adding a README and some other small minor changes. Hold on.

**Comment by VuiMuich** [comment]
Looking very nice, thanks for all the effort.
The up script isn't actually not very basic, but I don't really mind 😃
It will probably take till tomorrow for me to do a final review BBC and merge.

**Comment by simtd** [comment]
It was as basic as I could make it while still showing how to use lemonbar properly. Also the fact that there can be multiple workspaces adds some complexity.

**Comment by VuiMuich** [comment]
This is excelent! Thank you so much! :pray:

**Pull request merged**
