### PR TITLE
Swap for new copr repo

### PR DESCRIPTION
**Pull request by TH3-S4LM0N**
### Description
As the atim/leftwm copr has been broken since November I created a new one (`th3-s4lm0n/leftwm`). I would appreciate if anybody using Fedora could test this for a day or two because "it works on my machine" isn't especially reassuring to me. This is the first copr I've made so some testing can't hurt.

### CODE REVIEW

**Comment by VuiMuich** [comment]
Awesome, thanks!

tagging @NicTanghe for a test spin if possible.

**Comment by NicTanghe** [comment]
Hello,
I have switched to RHEL8 and don't really have spare storage space.

**Comment by VuiMuich** [comment]
I guess we proceed then, and react if there is some complaints.

Thanks a lot for the effort @TH3-S4LM0N!

**Comment by VuiMuich** [comment]
Hey @TH3-S4LM0N, just wanted to ping you, to let you know we bumped to `0.4.1`. Not sure if that requries any manual work on the copr package. At least its no such severe things in this update as it was with the `0.4.0` release :joy:

**Comment by TH3-S4LM0N** [comment]
I just have to bump the version number, thanks for notifying me though!

**Comment by TH3-S4LM0N** [comment]
@VuiMuich is `0.4.1` going to have a github tag/release?

**Comment by VuiMuich** [comment]
The tag is already published, but the release is in the making. 
I just learned, that the release has its own hash, so you might want to wait for it to be published.
Sorry for waking you early :grimacing:

**Pull request merged**
