### PR TITLE
bump MSRV to 1.57.0

### PR DESCRIPTION
**Pull request by VuiMuich**
# Description

Bump MSRV to 1.57.0 to suffice dependency needs for #821.
~~Our most consarvative target distro has been NetBSD and they use currently 1.62.1, yet I'd like to keep the bump as low as possible.~~

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Updated user documentation:

Please insert user documentation that should be updated (as in the wiki).

See [CONTRIBUTING.md User Documentation section](../CONTRIBUTING.md#user-documentation) for further details.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [ ] Ran `make test-full` locally with no errors or warnings reported
- [ ] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by 0323pin** [comment]
Hmm ...
> Our most consarvative target distro has been NetBSD and they use currently 1.62.1

Debian sid is using 1.59

**Comment by VuiMuich** [comment]
Ok, I'll take it back and state the opposite:Not our most [...] 1.62.1. :stuck_out_tongue_closed_eyes: 

What means 'allowed'?

**Comment by 0323pin** [comment]
@VuiMuich It means we don't support builds with Rust < 1.56
Say you would install rust-1.54, if you then try to build anything with it, the system will refuse to do it and point out that the minimum supported version is 1.56.

**Comment by VuiMuich** [comment]
Oh, my tired 🧠 totally skipped the 'lowest' part. Now that makes a lot more sense.

**Pull request merged**
