### PR TITLE
Handling Normal window type as non transient

### PR DESCRIPTION
**Pull request by lkadalski**
This is answer for problem with Intellij. Issue explained in [ticket](https://github.com/leftwm/leftwm/issues/488)

Signed-off-by: lkadalski <kadalski.lukasz@gmail.com>

### CODE REVIEW

**Comment by AethanFoot** [comment]
I have also found another place where this would fix, which if with timeshift (or probably any other app which does the same). This issue is that timeshift creates a new normal window and hides the original window when going to the settings page (instead of dialog, and which isn't very twm friendly). This cause a floating window which takes the whole screen as the parent is hidden so our sizing doesnt work properly, with no parent accessible. Anything that works like this is just bad app design, but this change should prevent us creating any extra side effects.

However I would say it would be better to address in window_handler, where we actually set the window floating. As knowing the windows parent should still be stored in case we want to use it.

Thanks.

**Comment by lex148** [comment]
@lkadalski this is great. I am out of the office until the 1st, so its going to take be just a bit to test this but cant wait to get it merged. little fixes like this really make such a big difference.  

If anyone else gets a chance to test please give it a thumbs up so I know. I'm a little unavailable this week.

**Comment by lkadalski** [comment]
Thanks, this is mainly done by research work of @hertg
Do you think it should be moved to other component as @AethanFoot suggested ?

**Comment by hertg** [comment]
I tested it on my machine and can confirm that it resolves the issue :tada: 
Are there any potential side effects of this update? I am happy to test those out as well.

@lkadalski 
Can you update your branch to the latest upstream? I would be willing to switch my local installation to your branch and see if something comes up in my day-to-day work.

**Comment by lkadalski** [comment]
Updated @hertg 
I think that someone mentioned in your research that is bad design when one Normal window creates new normal window as transient. It'd rather dialog etc.
But maybe **there is** some program which acts like this and it's expected. I'm not aware of any of those.
Currently I'm using Brave, Insomnia, Intellij, Alacritty, Nemo(sometimes) in many instances and don't have any unexpected behavior with this setup.
Please don't trust me though, and test your workflow :)

**Pull request merged**
